Analyzing The Dataset

In [88]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import pickle
import matplotlib as plt

In [24]:
g = pd.read_csv("phishing_site_urls.csv")
g

FILENAME                                                URL  \
0        521848.txt                   https://www.southbankmosaics.com   
1         31372.txt                           https://www.uni-mainz.de   
2        597387.txt                     https://www.voicefmradio.co.uk   
3        554095.txt                        https://www.sfnmjournal.com   
4        151578.txt                 https://www.rewildingargentina.org   
...             ...                                                ...   
235790   660997.txt                     https://www.skincareliving.com   
235791    77185.txt                      https://www.winchester.gov.uk   
235792   622132.txt                    https://www.nononsensedesign.be   
235793  7503962.txt  https://patient-cell-40f5.updatedlogmylogin.wo...   
235794   384822.txt                 https://www.alternativefinland.com   

        URLLength                                           Domain  \
0              31                         www.southbankmosaics.com   
1              23                                 www.uni-mainz.de   
2              29                           www.voicefmradio.co.uk   
3              26                              www.sfnmjournal.com   
4              33                       www.rewildingargentina.org   
...           ...                                              ...   
235790         29                           www.skincareliving.com   
235791         28                            www.winchester.gov.uk   
235792         30                          www.nononsensedesign.be   
235793         55  patient-cell-40f5.updatedlogmylogin.workers.dev   
235794         33                       www.alternativefinland.com   

        DomainLength  IsDomainIP  TLD  URLSimilarityIndex  \
0                 24           0  com          100.000000   
1                 16           0   de          100.000000   
2                 22           0   uk          100.000000   
3                 19           0  com          100.000000   
4                 26           0  org          100.000000   
...              ...         ...  ...                 ...   
235790            22           0  com          100.000000   
235791            21           0   uk          100.000000   
235792            23           0   be          100.000000   
235793            47           0  dev           28.157537   
235794            26           0  com          100.000000   

        CharContinuationRate  TLDLegitimateProb  ...  Pay  Crypto  \
0                   1.000000           0.522907  ...    0       0   
1                   0.666667           0.032650  ...    0       0   
2                   0.866667           0.028555  ...    0       0   
3                   1.000000           0.522907  ...    1       1   
4                   1.000000           0.079963  ...    1       0   
...                      ...                ...  ...  ...     ...   
235790              1.000000           0.522907  ...    1       0   
235791              0.785714           0.028555  ...    1       0   
235792              1.000000           0.003319  ...    0       0   
235793              0.465116           0.000961  ...    0       0   
235794              1.000000           0.522907  ...    0       0   

        HasCopyrightInfo  NoOfImage  NoOfCSS  NoOfJS  NoOfSelfRef  \
0                      1         34       20      28          119   
1                      1         50        9       8           39   
2                      1         10        2       7           42   
3                      1          3       27      15           22   
4                      1        244       15      34           72   
...                  ...        ...      ...     ...          ...   
235790                 1         51        7      21          187   
235791                 0         50        1       7           88   
235792                 1         27       10      30           58   
235793                 0     

In [49]:
f = g[["URLLength","DomainLength","TLD","NoOfLettersInURL","NoOfDegitsInURL","NoOfEqualsInURL","NoOfQMarkInURL","NoOfAmpersandInURL","NoOfOtherSpecialCharsInURL","IsHTTPS","NoOfCSS","NoOfJS","NoOfSelfRef","NoOfEmptyRef","NoOfExternalRef"]]
f = f.drop("TLD",axis=1)
f

URLLength  DomainLength  NoOfLettersInURL  NoOfDegitsInURL  \
0              31            24                18                0   
1              23            16                 9                0   
2              29            22                15                0   
3              26            19                13                0   
4              33            26                20                0   
...           ...           ...               ...              ...   
235790         29            22                16                0   
235791         28            21                14                0   
235792         30            23                17                0   
235793         55            47                39                3   
235794         33            26                20                0   

        NoOfEqualsInURL  NoOfQMarkInURL  NoOfAmpersandInURL  \
0                     0               0                   0   
1                     0               0                   0   
2                     0               0                   0   
3                     0               0                   0   
4                     0               0                   0   
...                 ...             ...                 ...   
235790                0               0                   0   
235791                0               0                   0   
235792                0               0                   0   
235793                0               0                   0   
235794                0               0                   0   

        NoOfOtherSpecialCharsInURL  IsHTTPS  NoOfCSS  NoOfJS  NoOfSelfRef  \
0                                1        1       20      28          119   
1                                2        1        9       8           39   
2                                2        1        2       7           42   
3                                1        1       27      15           22   
4                                1        1       15      34           72   
...                            ...      ...      ...     ...          ...   
235790                           1        1        7      21          187   
235791                           2        1        1       7           88   
235792                           1        1       10      30           58   
235793                           5        1        0       3            0   
235794                           1        1        6      18          256   

        NoOfEmptyRef  NoOfExternalRef  
0                  0              124  
1                  0              217  
2                  2                5  
3                  1               31  
4                  1               85  
...              ...              ...  
235790             2              191  
235791             0               31  
235792             2               67  
235793             0                0  
235794             0              261  

[235795 rows x 14 columns]

In [50]:
h = g[["label"]]
h 

label
0           1
1           1
2           1
3           1
4           1
...       ...
235790      1
235791      1
235792      1
235793      0
235794      1

[235795 rows x 1 columns]

Training and saving up the models

In [59]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression

In [60]:
x_train,x_test,y_train,y_test = train_test_split(f,h,test_size=0.3,random_state=40)

In [61]:
x_test

URLLength  DomainLength  NoOfLettersInURL  NoOfDegitsInURL  \
70246          26            18                13                3   
77980          28            21                15                0   
140969         25            18                12                0   
214837         21            13                 8                0   
231440         19             5                 9                0   
...           ...           ...               ...              ...   
207330         31            24                17                0   
131325         20            13                 7                0   
197881         52            35                29                7   
75800          19            12                 6                0   
89431          23            16                10                0   

        NoOfEqualsInURL  NoOfQMarkInURL  NoOfAmpersandInURL  \
70246                 0               0                   0   
77980                 0               0                   0   
140969                0               0                   0   
214837                0               0                   0   
231440                0               0                   0   
...                 ...             ...                 ...   
207330                0               0                   0   
131325                0               0                   0   
197881                0               0                   1   
75800                 0               0                   0   
89431                 0               0                   0   

        NoOfOtherSpecialCharsInURL  IsHTTPS  NoOfCSS  NoOfJS  NoOfSelfRef  \
70246                            2        1        2       2            2   
77980                            1        1       33      38           97   
140969                           1        1       12      19           40   
214837                           2        0        0       0            0   
231440                           2        1        1       3            5   
...                            ...      ...      ...     ...          ...   
207330                           2        1        7      26          136   
131325                           1        1        1       6            0   
197881                           7        1        0       0            0   
75800                            1        1       20      18          260   
89431                            1        1       15       6          115   

        NoOfEmptyRef  NoOfExternalRef  
70246              0                0  
77980             12               82  
140969             3               42  
214837             0                1  
231440             0                5  
...              ...              ...  
207330            67               14  
131325             2               12  
197881             0                1  
75800             25              263  
89431              0              121  

[70739 rows x 14 columns]

In [62]:
x_train

URLLength  DomainLength  NoOfLettersInURL  NoOfDegitsInURL  \
115101         47            41                15               20   
133396         25            18                12                0   
73322          26            19                12                0   
9180           24            17                11                0   
86916          42            33                24                5   
...           ...           ...               ...              ...   
93176          38            31                25                0   
211109         28            22                15                0   
30727          33            24                18                3   
112859         35            28                22                0   
142662         34            27                21                0   

        NoOfEqualsInURL  NoOfQMarkInURL  NoOfAmpersandInURL  \
115101                0               0                   0   
133396                0               0                   0   
73322                 0               0                   0   
9180                  0               0                   0   
86916                 0               0                   0   
...                 ...             ...                 ...   
93176                 0               0                   0   
211109                0               0                   0   
30727                 0               0                   0   
112859                0               0                   0   
142662                0               0                   0   

        NoOfOtherSpecialCharsInURL  IsHTTPS  NoOfCSS  NoOfJS  NoOfSelfRef  \
115101                           1        0        0       0            0   
133396                           1        1       32      30          106   
73322                            2        1       23      16          200   
9180                             1        1       23      13          111   
86916                            5        1        0       0            0   
...                            ...      ...      ...     ...          ...   
93176                            1        1        9      20            1   
211109                           2        0        0       0            0   
30727                            4        1        0       0            0   
112859                           1        1       36      11           54   
142662                           1        1        8      49          238   

        NoOfEmptyRef  NoOfExternalRef  
115101             0                1  
133396             0              113  
73322             13              225  
9180               0               17  
86916              0                3  
...              ...              ...  
93176              3               12  
211109             0                1  
30727              0                3  
112859             2               98  
142662             8               31  

[165056 rows x 14 columns]

In [63]:
lor = LogisticRegression()
lor.fit(x_train,y_train)


LogisticRegression()

In [64]:
pickle.dump(lor,open("LogisticModel.pkl","wb"))

In [65]:
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [66]:
pickle.dump(lr,open("LinearModel.pkl","wb"))

In [72]:
svm = SVC(kernel='rbf', C=1.0, gamma='scale', probability=True)
svm.fit(x_train,y_train)

SVC(probability=True)

In [75]:
pickle.dump(svm,open("SVMmodel.pkl","wb"))

In [73]:
y_pred1 = lr.predict(x_test)
y_pred2 = lor.predict(x_test)
y_pred3 = svm.predict(x_test)


In [69]:
y_pred1


array([[0.28143336],
       [1.02979906],
       [0.93007411],
       ...,
       [0.11827055],
       [0.98541497],
       [0.90520135]])

In [83]:
def convert_to_binary(arr):
    return np.where(arr >= 0.8, 1, 0)

y_pred1 = convert_to_binary(y_pred1)
y_pred1

array([[0],
       [1],
       [1],
       ...,
       [0],
       [1],
       [1]])

In [70]:
y_pred2

array([0, 1, 1, ..., 0, 1, 1], dtype=int64)

In [74]:
y_pred3

array([0, 1, 1, ..., 0, 1, 1], dtype=int64)

Checking out the accuracy Scores

In [78]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [80]:
#for the logistic Model
lor_accuracy = accuracy_score(y_test,y_pred2)
print('Accuracy of the Logistic regression model - ',lor_accuracy)

Accuracy of the Logistic regression model -  0.9985439432279224


In [81]:
#for the SVM model 
svm_accuracy = accuracy_score(y_test,y_pred3)
print('Accuracy of the SVM model - ', svm_accuracy)

Accuracy of the SVM model -  0.9885353199790781


In [84]:
#for the linear Model
lr_accuracy = accuracy_score(y_test,y_pred1)
print('Accuracy of the linear model - ',lr_accuracy)

Accuracy of the linear model -  0.9927055796660965


Confusion Matrix

In [87]:
#for linear Model
lr_cm = confusion_matrix(y_test,y_pred1)
print("Confusion Matrix for Linear model -\n",lr_cm)

Confusion Matrix for Linear model -
 [[29961   365]
 [  151 40262]]


In [89]:
#for logistic model 
lor_cm = confusion_matrix(y_test, y_pred2)
print("Confusion Matrix for Logistic model -\n",lor_cm)

Confusion Matrix for Logistic model -
 [[30229    97]
 [    6 40407]]


In [90]:
#for SVm model 
svm_cm = confusion_matrix(y_test,y_pred3)
print("Confusion Matrix for SVM model -\n",svm_cm)

Confusion Matrix for SVM model -
 [[30084   242]
 [  569 39844]]
